FROM ubuntu:latest

RUN apt update  
RUN apt install numpy 
RUN apt install torch 
RUN apt install opencv-python 
RUN apt install models 
RUN apt install util 
RUN apt install torchviion 
RUN apt install insightface_func 
RUN apt install options 
RUN apt install fractions 

COPY . .